import { supabaseAdmin } from "@/lib/supabase/admin";
import type { VariantInput } from "./productValidation";

// Checks every variant SKU being submitted against every other product's
// variants in the catalog. The product's own top-level SKU never needs
// this check — it's always server-generated by the atomic
// next_product_sku() counter and DB-unique-constrained, so it can never
// collide. `excludeProductId` is the product being edited (so its own
// existing variant rows about to be replaced don't flag as conflicts with
// themselves).
export async function findDuplicateSku(
  variants: VariantInput[],
  excludeProductId?: string
): Promise<string | null> {
  const candidateSkus = variants.map((v) => v.sku).filter((s): s is string => Boolean(s && s.trim()));
  if (candidateSkus.length === 0) return null;

  const { data, error } = await supabaseAdmin
    .from("product_variants")
    .select("id, product_id, sku")
    .in("sku", candidateSkus);

  if (error) {
    throw new Error(`SKU check failed: ${error.message}`);
  }

  const conflictingVariant = (data ?? []).find((v) => v.product_id !== excludeProductId);
  return conflictingVariant?.sku ?? null;
}
